website = {
    'Weather React': "https://weather-forecast-192305.appspot.com",
    'Tech Blog': "https://chronicle-170419.appspot.com",
    "Music Catalog": "http://ec2-54-236-32-135.compute-1.amazonaws.com",
    "Portfolio": "https://ian-agpawa.appspot.com",
    "Weather Forecast": "https://weather-169903.appspot.com",
    "TacoHub": "https://tacohub-155203.appspot.com" ,
    "Music Blog": "https://synchronicity-collective.appspot.com",
    "Simon Says": "https://simon-says-ia.herokuapp.com",
    "Monitor": "https://github.com/ianagpawa/monitor",
    "Random Quote Generator": "https://rand-quote-gen.herokuapp.com",
    "Image Search": "https://imgsearch-ia.herokuapp.com",
    "Tic Tac Toe": "https://ianagpawa.github.io/TickyTacky",
    "Javascript Calculator": "https://ianagpawa.github.io/calculator",
    "Pomodoro Productivity Timer": "https://pomodoro-timer-ia.herokuapp.com",
    "URL Shortener": "https://u-short.herokuapp.com",
    "Audacious": "https://github.com/ianagpawa/audacious",
    "Wikipedia Viewer": "https://wiki-it-ia.herokuapp.com",
    "Request Header Parser": "https://header-parser-ia.herokuapp.com",
    "TimeStamp": "https://timestamp-microservice-ia.herokuapp.com",
    "File Metadata": "https://metadata-ia.herokuapp.com",
    "Local Weather": "https://weather-ia.herokuapp.com",
    "Finance Tracker": "https://thawing-plains-40720.herokuapp.com/users/sign_in",
    "Tribute Page": "https://hunter-s-tribute.herokuapp.com",
    "Alpha Blog": "https://project-prometheus-alphablog.herokuapp.com",
    "Old Portfolio": "https://ian-agpawa.herokuapp.com"
}
